import Link from "next/link";
import { Button, Card } from "@mogd/ui";

const LOOP_STEPS = ["Assess", "Model", "Plan", "Execute", "Track", "Adapt"];

const VALUE_PROPS = [
  {
    eyebrow: "Assessment",
    title: "One structured intake",
    body: "Goal, body, training history, availability and nutrition — captured once, editable anytime from your profile.",
  },
  {
    eyebrow: "Nutrition",
    title: "Deterministic targets",
    body: "Calorie and macro targets are calculated and validated against fixed rules, not generated by a language model.",
  },
  {
    eyebrow: "Adaptation",
    title: "Plans that adjust",
    body: "Weekly check-ins propose real changes to your training and targets — reviewed by you, never applied automatically.",
  },
];

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center gap-16 px-6 py-16 sm:gap-20 sm:py-24">
      <div className="flex max-w-2xl flex-col items-center gap-6 text-center">
        <div className="flex flex-col items-center gap-2">
          <span className="font-display text-2xl font-semibold tracking-[0.18em] text-fg">
            MOG<span className="align-super text-base">D</span>
          </span>
          <span aria-hidden="true" className="h-0.5 w-7 rounded-full bg-accent" />
        </div>

        <h1 className="font-display text-4xl font-semibold leading-tight text-fg sm:text-5xl">
          Built from your assessment.
          <br />
          Adjusted from your results.
        </h1>

        <p className="max-w-md text-base text-fg-secondary sm:text-lg">
          A structured assessment sets your starting targets. Weekly check-ins adapt your plan
          from there — every change comes with a reason.
        </p>

        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link href="/sign-up">
            <Button>Create account</Button>
          </Link>
          <Link href="/sign-in">
            <Button variant="outline">Sign in</Button>
          </Link>
        </div>
      </div>

      <div className="flex flex-col items-center gap-3">
        <span className="text-xs font-semibold uppercase tracking-wide text-fg-secondary">
          How MOGᴰ works
        </span>
        <div className="flex flex-wrap items-center justify-center gap-x-2 gap-y-3">
          {LOOP_STEPS.map((step, i) => (
            <span key={step} className="flex items-center gap-2">
              <span className="rounded-full border border-border bg-surface px-3 py-1 text-xs font-semibold uppercase tracking-wide text-fg-secondary-alt">
                {step}
              </span>
              {i < LOOP_STEPS.length - 1 && (
                <span aria-hidden="true" className="text-fg-muted">
                  →
                </span>
              )}
            </span>
          ))}
        </div>
        <p className="text-xs text-fg-muted">Each cycle updates the model your plan is built from.</p>
      </div>

      <div className="grid w-full max-w-4xl gap-4 md:grid-cols-3">
        {VALUE_PROPS.map((item) => (
          <Card key={item.eyebrow} className="gap-2">
            <span className="text-xs font-semibold uppercase tracking-wide text-accent">{item.eyebrow}</span>
            <h2 className="text-base font-semibold text-fg">{item.title}</h2>
            <p className="text-sm text-fg-secondary">{item.body}</p>
          </Card>
        ))}
      </div>

      <p className="max-w-md text-center text-xs text-fg-muted">
        MOGᴰ trains around limitations you report. It does not diagnose or treat injuries.
      </p>
    </main>
  );
}
